package FenrirService.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import FenrirService.database.data.DataInterface;
import FenrirService.logger.FenrirLogging;

/*
 * 
 * MySQLConnector is used to make the connection to the database and manipulate data through the data models.
 * 
 */

public class MySQLConnector {
	private Connection connect = null;
	private Statement statement = null;
	private ResultSet resultSet = null;
	
	//open connection to db through drivehandler is required by most functions in this function
	private void openConnectionDatabase() {
		try {
			Class.forName("com.mysql.jdbc.Driver");
			connect = DriverManager.getConnection("jdbc:mysql://" + DatabaseData.getIp() + ":3306/" + 
					DatabaseData.getDatabase(),
					DatabaseData.getUsername(),
					DatabaseData.getPassword());
			statement = connect.createStatement();
		} catch (ClassNotFoundException | SQLException e) {
			FenrirLogging.getInstance().logSevere(e.toString());
		}
	}
	
	//read database uses a generic that extends Datainterface. every class that implements this interface 
	//can be used in this class to build select statements
	public <E extends DataInterface> E readDatabase(E e){
		try {
			openConnectionDatabase();
			resultSet = statement.executeQuery(e.buildSelect());
			e.setAll(resultSet);
			closeConnectionDatabase();
		} catch (SQLException ex) {
			FenrirLogging.getInstance().logSevere(ex.toString());
		}
		return e;
	}
	
	//The generic is replaced by data model and the data model is used to build the insert statement
	public <E extends DataInterface> void writeDatabase(E e){
		try {
			openConnectionDatabase();
			statement.executeUpdate(e.buildInsert());
			closeConnectionDatabase();
		} catch (SQLException ex) {
			FenrirLogging.getInstance().logSevere(ex.toString());
		}
	}
	
	//The generic is replced by data model and the data model builds the update statement
	public <E extends DataInterface> void updateDatabase(E e){
		try {
			openConnectionDatabase();
			statement.executeUpdate(e.buildUpdate());
			closeConnectionDatabase();
		} catch (SQLException ex) {
			FenrirLogging.getInstance().logSevere(ex.toString());
		}
	}
	
	//The generic is replced by data model and the data model builds the delete statement
	public <E extends DataInterface> void deleteDatabase(E e){
		try {
			e = readDatabase(e);
			openConnectionDatabase();
			statement.executeUpdate(e.buildDelete());
			closeConnectionDatabase();
		} catch (SQLException ex) {
			FenrirLogging.getInstance().logSevere(ex.toString());
		}
	}
	
	//Cleans up the resultSet, statement and connect objects by properly closing them.
	private void closeConnectionDatabase(){
		try {
		      if (resultSet != null) {
		        resultSet.close();
		      }
		      if (statement != null) {
		        statement.close();
		      }
		      if (connect != null) {
		        connect.close();
		      }
		    } catch (Exception e) { } //errors generated by this are in general irrelevant as they often mean it is already closed
	}
	
}
